# Generated by Django 3.2.12 on 2022-04-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='first_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='')),
                ('book', models.FileField(upload_to='')),
                ('clip', models.FileField(upload_to='')),
            ],
        ),
    ]
