# Generated by Django 3.2.12 on 2022-04-01 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='first_image',
            old_name='book',
            new_name='Book',
        ),
        migrations.RenameField(
            model_name='first_image',
            old_name='clip',
            new_name='Clip',
        ),
        migrations.RenameField(
            model_name='first_image',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='first_image',
            old_name='photo',
            new_name='Photo',
        ),
    ]
