# Generated by Django 3.2.12 on 2022-04-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('product_code', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('health_benefits', models.TextField()),
            ],
        ),
    ]
