# Generated by Django 3.2.12 on 2022-04-16 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulses', '0002_ppl_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='p',
            new_name='product_image',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='name',
            new_name='product_name',
        ),
    ]
