# Generated by Django 3.2.12 on 2022-04-16 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulses', '0003_auto_20220416_1157'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='food',
            new_name='snacks',
        ),
    ]
