# Generated by Django 3.2.12 on 2022-04-16 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pulses', '0004_rename_food_snacks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ppl',
        ),
    ]
