# Generated by Django 3.2.12 on 2022-04-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='suma',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
